import { Product, Store } from '../types';

// Helper: returns local path with Unsplash fallback.
// The <img> tag in components uses onError to swap to the fallback URL.
export function imgWithFallback(localPath: string, fallbackUrl: string) {
  return { src: localPath, fallback: fallbackUrl };
}

// ─────────────────────────────────────────────────────────────────────────────
// STORES
// ─────────────────────────────────────────────────────────────────────────────
export const mockShoppingStores: Store[] = [
  { id: 's1', name: 'Mhetha Stores',  logoUrl: '/images/stores/mhetha-stores/logo.jpg',        fallbackLogoUrl: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=200&h=200&fit=crop', rating: 4.5, category: 'grocery', isOpen: true },
  { id: 's2', name: 'Vishal Mart',    logoUrl: '/images/stores/vishal-mart/logo.jpg',           fallbackLogoUrl: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?w=200&h=200&fit=crop', rating: 4.2, category: 'grocery', isOpen: true },
  { id: 's3', name: 'RR Bazar',       logoUrl: '/images/stores/rr-bazar/logo.jpg',              fallbackLogoUrl: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=200&h=200&fit=crop', rating: 4.6, category: 'grocery', isOpen: true },
  { id: 's4', name: 'Nandhini KGF',   logoUrl: '/images/stores/nandhini-kgf/logo.jpg',          fallbackLogoUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=200&h=200&fit=crop', rating: 4.9, category: 'grocery', isOpen: true },
];

export const mockFoodStores: Store[] = [
  { id: 'f1', name: 'Bakio',               logoUrl: '/images/stores/bakio/logo.jpg',              fallbackLogoUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=200&h=200&fit=crop', rating: 4.7, category: 'food', isOpen: true },
  { id: 'f2', name: 'Mayura',              logoUrl: '/images/stores/mayura/logo.jpg',             fallbackLogoUrl: 'https://images.unsplash.com/photo-1557308536-ee471ef2c390?w=200&h=200&fit=crop', rating: 4.4, category: 'food', isOpen: true },
  { id: 'f3', name: 'Ambur Biriyani KGF', logoUrl: '/images/stores/ambur-biriyani-kgf/logo.jpg', fallbackLogoUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=200&h=200&fit=crop', rating: 4.8, category: 'food', isOpen: true },
  { id: 'f4', name: 'Al Baik',            logoUrl: '/images/stores/al-baik/logo.jpg',            fallbackLogoUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=200&h=200&fit=crop', rating: 4.5, category: 'food', isOpen: true },
  { id: 'f5', name: 'Al Naz',             logoUrl: '/images/stores/al-naz/logo.jpg',             fallbackLogoUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=200&h=200&fit=crop', rating: 4.3, category: 'food', isOpen: true },
];

// ─────────────────────────────────────────────────────────────────────────────
// SHOPPING PRODUCTS (~10 per store)
// ─────────────────────────────────────────────────────────────────────────────

// MHETHA STORES (Groceries)
const mhethaProducts: Product[] = [
  { id: 'ms01', name: 'Maggi 2-Minute Noodles',      price: 2800,  storeId: 's1', storeName: 'Mhetha Stores', category: 'grocery', description: '140 g (Pack of 2) • Instant masala noodles', deliveryEtaMinutes: 10, inStock: true, imageUrl: '/images/products/maggi-noodles.jpg',          fallbackImageUrl: 'https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?w=400&h=400&fit=crop' },
  { id: 'ms02', name: 'Fortune Sunflower Oil',        price: 13500, storeId: 's1', storeName: 'Mhetha Stores', category: 'grocery', description: '1 L Pouch • Refined sunflower oil',            deliveryEtaMinutes: 10, inStock: true, imageUrl: '/images/products/sunflower-oil.jpg',          fallbackImageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&h=400&fit=crop' },
  { id: 'ms03', name: 'Tata Tea Gold',               price: 4500,  storeId: 's1', storeName: 'Mhetha Stores', category: 'grocery', description: '250 g • Strong & aromatic tea',                deliveryEtaMinutes: 10, inStock: true, imageUrl: '/images/products/tata-tea.jpg',              fallbackImageUrl: 'https://images.unsplash.com/photo-1556742044-3c52d6e88c62?w=400&h=400&fit=crop' },
  { id: 'ms04', name: 'Parle-G Gold Biscuits',       price: 1000,  storeId: 's1', storeName: 'Mhetha Stores', category: 'grocery', description: '450 g • Classic glucose biscuits',             deliveryEtaMinutes: 10, inStock: true, imageUrl: '/images/products/parle-g.jpg',               fallbackImageUrl: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400&h=400&fit=crop' },
  { id: 'ms05', name: 'Lays Classic Salted Chips',   price: 2000,  storeId: 's1', storeName: 'Mhetha Stores', category: 'grocery', description: '73 g • Crispy potato chips',                   deliveryEtaMinutes: 10, inStock: true, imageUrl: '/images/products/lays-chips.jpg',            fallbackImageUrl: 'https://images.unsplash.com/photo-1600952841320-db92ec4047ca?w=400&h=400&fit=crop' },
  { id: 'ms06', name: 'Surf Excel Quick Wash',       price: 9500,  storeId: 's1', storeName: 'Mhetha Stores', category: 'grocery', description: '1 kg • Detergent powder',                      deliveryEtaMinutes: 10, inStock: true, imageUrl: '/images/products/surf-excel.jpg',            fallbackImageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop' },
  { id: 'ms07', name: 'Dove Soap Bar',               price: 3500,  storeId: 's1', storeName: 'Mhetha Stores', category: 'grocery', description: '3×75 g Pack • Moisturizing beauty bar',       deliveryEtaMinutes: 10, inStock: true, imageUrl: '/images/products/dove-soap.jpg',             fallbackImageUrl: 'https://images.unsplash.com/photo-1547496502-affa22d38842?w=400&h=400&fit=crop' },
  { id: 'ms08', name: 'Head & Shoulders Shampoo',    price: 17500, storeId: 's1', storeName: 'Mhetha Stores', category: 'grocery', description: '340 ml • Anti-dandruff shampoo',               deliveryEtaMinutes: 10, inStock: true, imageUrl: '/images/products/head-shoulders.jpg',        fallbackImageUrl: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=400&h=400&fit=crop' },
  { id: 'ms09', name: 'Tata Salt (Iodized)',         price: 2500,  storeId: 's1', storeName: 'Mhetha Stores', category: 'grocery', description: '1 kg • Vacuum evaporated iodized salt',        deliveryEtaMinutes: 10, inStock: true, imageUrl: '/images/products/tata-salt.jpg',             fallbackImageUrl: 'https://images.unsplash.com/photo-1627464987747-0e6977759b32?w=400&h=400&fit=crop' },
  { id: 'ms10', name: 'Lijjat Papad',               price: 6000,  storeId: 's1', storeName: 'Mhetha Stores', category: 'grocery', description: '200 g • Crispy urad dal papads',               deliveryEtaMinutes: 10, inStock: true, imageUrl: '/images/products/lijjat-papad.jpg',          fallbackImageUrl: 'https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=400&h=400&fit=crop' },
];

// VISHAL MART (Groceries)
const vishalProducts: Product[] = [
  { id: 'vm01', name: 'Aashirvaad Chakki Atta',     price: 6500,  storeId: 's2', storeName: 'Vishal Mart', category: 'grocery', description: '1 kg • Premium whole wheat flour',             deliveryEtaMinutes: 15, inStock: true, imageUrl: '/images/products/atta.jpg',                  fallbackImageUrl: 'https://images.unsplash.com/photo-1574316071802-0d684efa7bf5?w=400&h=400&fit=crop' },
  { id: 'vm02', name: 'India Gate Basmati Rice',    price: 22000, storeId: 's2', storeName: 'Vishal Mart', category: 'grocery', description: '5 kg • Classic aged basmati rice',             deliveryEtaMinutes: 15, inStock: true, imageUrl: '/images/products/basmati-rice.jpg',           fallbackImageUrl: 'https://images.unsplash.com/photo-1536304993881-ff86d42547e9?w=400&h=400&fit=crop' },
  { id: 'vm03', name: 'Tata Salt (Iodized)',        price: 2500,  storeId: 's2', storeName: 'Vishal Mart', category: 'grocery', description: '1 kg • Vacuum evaporated iodized salt',       deliveryEtaMinutes: 15, inStock: true, imageUrl: '/images/products/tata-salt.jpg',             fallbackImageUrl: 'https://images.unsplash.com/photo-1627464987747-0e6977759b32?w=400&h=400&fit=crop' },
  { id: 'vm04', name: 'Tata Sugar',                 price: 5000,  storeId: 's2', storeName: 'Vishal Mart', category: 'grocery', description: '1 kg • Fine grain refined sugar',             deliveryEtaMinutes: 15, inStock: true, imageUrl: '/images/products/sugar.jpg',                  fallbackImageUrl: 'https://images.unsplash.com/photo-1584351583219-c52f96b58d0a?w=400&h=400&fit=crop' },
  { id: 'vm05', name: 'Toor Dal (Arhar)',           price: 18000, storeId: 's2', storeName: 'Vishal Mart', category: 'grocery', description: '1 kg • Premium toor dal',                     deliveryEtaMinutes: 15, inStock: true, imageUrl: '/images/products/toor-dal.jpg',               fallbackImageUrl: 'https://images.unsplash.com/photo-1515543904379-3d757afe72e4?w=400&h=400&fit=crop' },
  { id: 'vm06', name: 'Maggi 2-Minute Noodles',    price: 2800,  storeId: 's2', storeName: 'Vishal Mart', category: 'grocery', description: '140 g (Pack of 2) • Instant masala noodles',  deliveryEtaMinutes: 15, inStock: true, imageUrl: '/images/products/maggi-noodles.jpg',          fallbackImageUrl: 'https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?w=400&h=400&fit=crop' },
  { id: 'vm07', name: 'Colgate Toothpaste',        price: 9800,  storeId: 's2', storeName: 'Vishal Mart', category: 'grocery', description: '300 g • Strong Teeth whitening paste',        deliveryEtaMinutes: 15, inStock: true, imageUrl: '/images/products/colgate.jpg',                fallbackImageUrl: 'https://images.unsplash.com/photo-1601612628452-9e99ced43524?w=400&h=400&fit=crop' },
  { id: 'vm08', name: 'Lifebuoy Soap',             price: 2800,  storeId: 's2', storeName: 'Vishal Mart', category: 'grocery', description: '125 g × 3 • Germ protection bar',             deliveryEtaMinutes: 15, inStock: true, imageUrl: '/images/products/lifebuoy.jpg',               fallbackImageUrl: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=400&h=400&fit=crop' },
  { id: 'vm09', name: 'Vim Dish Wash Liquid',      price: 5500,  storeId: 's2', storeName: 'Vishal Mart', category: 'grocery', description: '750 ml • Lemon-powered dish cleaner',         deliveryEtaMinutes: 15, inStock: true, imageUrl: '/images/products/vim.jpg',                    fallbackImageUrl: 'https://images.unsplash.com/photo-1617107822657-e7fb280e64d4?w=400&h=400&fit=crop' },
  { id: 'vm10', name: 'Harpic Toilet Cleaner',     price: 14900, storeId: 's2', storeName: 'Vishal Mart', category: 'grocery', description: '500 ml • 100% stain removal',                 deliveryEtaMinutes: 15, inStock: true, imageUrl: '/images/products/harpic.jpg',                 fallbackImageUrl: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=400&h=400&fit=crop' },
];

// RR BAZAR (Groceries)
const rrBazarProducts: Product[] = [
  { id: 'rr01', name: 'Aashirvaad Chakki Atta',    price: 6500,  storeId: 's3', storeName: 'RR Bazar', category: 'grocery', description: '1 kg • Premium whole wheat flour',             deliveryEtaMinutes: 12, inStock: true, imageUrl: '/images/products/atta.jpg',                  fallbackImageUrl: 'https://images.unsplash.com/photo-1574316071802-0d684efa7bf5?w=400&h=400&fit=crop' },
  { id: 'rr02', name: 'Sona Masoori Rice',         price: 12000, storeId: 's3', storeName: 'RR Bazar', category: 'grocery', description: '5 kg • Everyday soft rice',                    deliveryEtaMinutes: 12, inStock: true, imageUrl: '/images/products/sona-rice.jpg',              fallbackImageUrl: 'https://images.unsplash.com/photo-1536304993881-ff86d42547e9?w=400&h=400&fit=crop' },
  { id: 'rr03', name: 'Fortune Sunflower Oil',     price: 13500, storeId: 's3', storeName: 'RR Bazar', category: 'grocery', description: '1 L Pouch • Refined sunflower oil',            deliveryEtaMinutes: 12, inStock: true, imageUrl: '/images/products/sunflower-oil.jpg',          fallbackImageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&h=400&fit=crop' },
  { id: 'rr04', name: 'Tata Sugar',                price: 5000,  storeId: 's3', storeName: 'RR Bazar', category: 'grocery', description: '1 kg • Fine grain refined sugar',             deliveryEtaMinutes: 12, inStock: true, imageUrl: '/images/products/sugar.jpg',                  fallbackImageUrl: 'https://images.unsplash.com/photo-1584351583219-c52f96b58d0a?w=400&h=400&fit=crop' },
  { id: 'rr05', name: 'Moong Dal (Split)',         price: 16500, storeId: 's3', storeName: 'RR Bazar', category: 'grocery', description: '500 g • Split green moong dal',               deliveryEtaMinutes: 12, inStock: true, imageUrl: '/images/products/moong-dal.jpg',              fallbackImageUrl: 'https://images.unsplash.com/photo-1515543904379-3d757afe72e4?w=400&h=400&fit=crop' },
  { id: 'rr06', name: 'Chana Dal',                price: 14000, storeId: 's3', storeName: 'RR Bazar', category: 'grocery', description: '500 g • Bengal gram split dal',              deliveryEtaMinutes: 12, inStock: true, imageUrl: '/images/products/chana-dal.jpg',              fallbackImageUrl: 'https://images.unsplash.com/photo-1515543904379-3d757afe72e4?w=400&h=400&fit=crop' },
  { id: 'rr07', name: 'MDH Garam Masala',         price: 9000,  storeId: 's3', storeName: 'RR Bazar', category: 'grocery', description: '100 g • Premium spice blend',                  deliveryEtaMinutes: 12, inStock: true, imageUrl: '/images/products/garam-masala.jpg',           fallbackImageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop' },
  { id: 'rr08', name: 'Everest Sambar Masala',    price: 7500,  storeId: 's3', storeName: 'RR Bazar', category: 'grocery', description: '100 g • South Indian spice mix',              deliveryEtaMinutes: 12, inStock: true, imageUrl: '/images/products/sambar-masala.jpg',          fallbackImageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop' },
  { id: 'rr09', name: 'Tata Salt (Iodized)',      price: 2500,  storeId: 's3', storeName: 'RR Bazar', category: 'grocery', description: '1 kg • Vacuum evaporated iodized salt',       deliveryEtaMinutes: 12, inStock: true, imageUrl: '/images/products/tata-salt.jpg',             fallbackImageUrl: 'https://images.unsplash.com/photo-1627464987747-0e6977759b32?w=400&h=400&fit=crop' },
  { id: 'rr10', name: 'Nescafé Classic Coffee',   price: 29900, storeId: 's3', storeName: 'RR Bazar', category: 'grocery', description: '200 g • Instant coffee powder',               deliveryEtaMinutes: 12, inStock: true, imageUrl: '/images/products/nescafe.jpg',                fallbackImageUrl: 'https://images.unsplash.com/photo-1497515114629-f71d768fd07c?w=400&h=400&fit=crop' },
];

// NANDHINI KGF (Dairy)
const nandhiniProducts: Product[] = [
  { id: 'nd01', name: 'Nandini Pasteurised Milk',  price: 2400,  storeId: 's4', storeName: 'Nandhini KGF', category: 'grocery', description: '500 ml • Fresh daily toned milk (3% fat)',     deliveryEtaMinutes: 8,  inStock: true, imageUrl: '/images/products/nandini-milk.jpg',          fallbackImageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&h=400&fit=crop' },
  { id: 'nd02', name: 'Nandini Fresh Curd',        price: 2500,  storeId: 's4', storeName: 'Nandhini KGF', category: 'grocery', description: '500 g • Thick pasteurized curd',               deliveryEtaMinutes: 8,  inStock: true, imageUrl: '/images/products/nandini-curd.jpg',          fallbackImageUrl: 'https://images.unsplash.com/photo-1558231206-8d6263595166?w=400&h=400&fit=crop' },
  { id: 'nd03', name: 'Nandini Pure Ghee',         price: 16500, storeId: 's4', storeName: 'Nandhini KGF', category: 'grocery', description: '200 ml • Rich aromatic pure cow ghee',         deliveryEtaMinutes: 8,  inStock: true, imageUrl: '/images/products/nandini-ghee.jpg',          fallbackImageUrl: 'https://images.unsplash.com/photo-1623880550478-f6ff67140e43?w=400&h=400&fit=crop' },
  { id: 'nd04', name: 'Nandini Paneer',            price: 11000, storeId: 's4', storeName: 'Nandhini KGF', category: 'grocery', description: '200 g • Fresh soft cottage cheese',             deliveryEtaMinutes: 8,  inStock: true, imageUrl: '/images/products/paneer.jpg',                fallbackImageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400&h=400&fit=crop' },
  { id: 'nd05', name: 'Nandini Butter',            price: 6500,  storeId: 's4', storeName: 'Nandhini KGF', category: 'grocery', description: '100 g • Salted white butter',                  deliveryEtaMinutes: 8,  inStock: true, imageUrl: '/images/products/butter.jpg',                fallbackImageUrl: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=400&h=400&fit=crop' },
  { id: 'nd06', name: 'Nandini Buttermilk',        price: 1500,  storeId: 's4', storeName: 'Nandhini KGF', category: 'grocery', description: '200 ml Tetrapack • Chilled spiced buttermilk', deliveryEtaMinutes: 8,  inStock: true, imageUrl: '/images/products/buttermilk.jpg',             fallbackImageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&h=400&fit=crop' },
  { id: 'nd07', name: 'Nandini Peda',              price: 8000,  storeId: 's4', storeName: 'Nandhini KGF', category: 'grocery', description: '250 g • Classic milk-based sweet',             deliveryEtaMinutes: 8,  inStock: true, imageUrl: '/images/products/peda.jpg',                  fallbackImageUrl: 'https://images.unsplash.com/photo-1624471580456-ef8e35ac2d6a?w=400&h=400&fit=crop' },
  { id: 'nd08', name: 'Nandini Flavoured Milk',    price: 3500,  storeId: 's4', storeName: 'Nandhini KGF', category: 'grocery', description: '200 ml • Badam or Chocolate flavour',          deliveryEtaMinutes: 8,  inStock: true, imageUrl: '/images/products/flavoured-milk.jpg',        fallbackImageUrl: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400&h=400&fit=crop' },
  { id: 'nd09', name: 'Amul Cheese Slices',        price: 12000, storeId: 's4', storeName: 'Nandhini KGF', category: 'grocery', description: '10 Slices • Ready-to-use cheese',              deliveryEtaMinutes: 8,  inStock: true, imageUrl: '/images/products/cheese-slices.jpg',         fallbackImageUrl: 'https://images.unsplash.com/photo-1552767059-ce182ead6c1b?w=400&h=400&fit=crop' },
  { id: 'nd10', name: 'Nandini Sweet Lassi',       price: 4500,  storeId: 's4', storeName: 'Nandhini KGF', category: 'grocery', description: '500 ml • Chilled rose-flavoured sweet lassi',  deliveryEtaMinutes: 8,  inStock: true, imageUrl: '/images/products/sweet-lassi.jpg',           fallbackImageUrl: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=400&h=400&fit=crop' },
];

export const mockShoppingProducts: Product[] = [
  ...mhethaProducts,
  ...vishalProducts,
  ...rrBazarProducts,
  ...nandhiniProducts,
];

// ─────────────────────────────────────────────────────────────────────────────
// FOOD PRODUCTS (~10 per store)
// ─────────────────────────────────────────────────────────────────────────────

// BAKIO (Bakery)
const bakioProducts: Product[] = [
  { id: 'ba01', name: 'Classic Egg Puff',        price: 2000,  storeId: 'f1', storeName: 'Bakio', category: 'food', description: '1 Piece • Flaky golden pastry with spiced egg',       deliveryEtaMinutes: 15, inStock: true, imageUrl: '/images/products/egg-puff.jpg',             fallbackImageUrl: 'https://images.unsplash.com/photo-1602492931448-f60879c31403?w=400&h=400&fit=crop' },
  { id: 'ba02', name: 'Fresh Milk Bread',        price: 4000,  storeId: 'f1', storeName: 'Bakio', category: 'food', description: '400 g • Soft freshly baked white bread loaf',         deliveryEtaMinutes: 15, inStock: true, imageUrl: '/images/products/milk-bread.jpg',            fallbackImageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=400&fit=crop' },
  { id: 'ba03', name: 'Black Forest Cake',       price: 45000, storeId: 'f1', storeName: 'Bakio', category: 'food', description: '500 g • Chocolate sponge with cherry & cream',        deliveryEtaMinutes: 20, inStock: true, imageUrl: '/images/products/black-forest-cake.jpg',    fallbackImageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=400&fit=crop' },
  { id: 'ba04', name: 'Butter Cookies',          price: 8000,  storeId: 'f1', storeName: 'Bakio', category: 'food', description: '400 g Tin • Freshly baked butter cookies',            deliveryEtaMinutes: 15, inStock: true, imageUrl: '/images/products/butter-cookies.jpg',        fallbackImageUrl: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=400&h=400&fit=crop' },
  { id: 'ba05', name: 'Rusks',                   price: 6000,  storeId: 'f1', storeName: 'Bakio', category: 'food', description: '350 g • Twice-baked crispy toast fingers',            deliveryEtaMinutes: 15, inStock: true, imageUrl: '/images/products/rusks.jpg',                 fallbackImageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop' },
  { id: 'ba06', name: 'Cream Buns',              price: 2500,  storeId: 'f1', storeName: 'Bakio', category: 'food', description: '2 Pieces • Fluffy buns filled with sweet cream',      deliveryEtaMinutes: 15, inStock: true, imageUrl: '/images/products/cream-buns.jpg',            fallbackImageUrl: 'https://images.unsplash.com/photo-1550617931-e17a7b70dce2?w=400&h=400&fit=crop' },
  { id: 'ba07', name: 'Chocolate Truffle Cake',  price: 55000, storeId: 'f1', storeName: 'Bakio', category: 'food', description: '500 g • Rich dark chocolate ganache cake',            deliveryEtaMinutes: 25, inStock: true, imageUrl: '/images/products/chocolate-cake.jpg',        fallbackImageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=400&fit=crop' },
  { id: 'ba08', name: 'Chicken Patties',         price: 3000,  storeId: 'f1', storeName: 'Bakio', category: 'food', description: '1 Piece • Crispy chicken in puff pastry',             deliveryEtaMinutes: 15, inStock: true, imageUrl: '/images/products/chicken-patties.jpg',       fallbackImageUrl: 'https://images.unsplash.com/photo-1602492931448-f60879c31403?w=400&h=400&fit=crop' },
  { id: 'ba09', name: 'Birthday Candles Set',    price: 5000,  storeId: 'f1', storeName: 'Bakio', category: 'food', description: '10 Candles + 1 Star • Celebration set',               deliveryEtaMinutes: 15, inStock: true, imageUrl: '/images/products/birthday-candles.jpg',      fallbackImageUrl: 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=400&h=400&fit=crop' },
  { id: 'ba10', name: 'Pineapple Pastry',        price: 9000,  storeId: 'f1', storeName: 'Bakio', category: 'food', description: '2 Pieces • Chilled pineapple cream pastry',           deliveryEtaMinutes: 20, inStock: true, imageUrl: '/images/products/pineapple-pastry.jpg',      fallbackImageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=400&h=400&fit=crop' },
];

// MAYURA (Bakery)
const mayuraProducts: Product[] = [
  { id: 'my01', name: 'Veg Aloo Puff',           price: 1500,  storeId: 'f2', storeName: 'Mayura', category: 'food', description: '1 Piece • Crispy pastry with spiced potato',         deliveryEtaMinutes: 15, inStock: true, imageUrl: '/images/products/veg-puff.jpg',              fallbackImageUrl: 'https://images.unsplash.com/photo-1587318712395-6d04fc4db04f?w=400&h=400&fit=crop' },
  { id: 'my02', name: 'Dilpasand',               price: 3500,  storeId: 'f2', storeName: 'Mayura', category: 'food', description: '1 Piece • Traditional KGF sweet coconut pie',        deliveryEtaMinutes: 15, inStock: true, imageUrl: '/images/products/dilpasand.jpg',             fallbackImageUrl: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=400&h=400&fit=crop' },
  { id: 'my03', name: 'Fresh Milk Bread',        price: 3500,  storeId: 'f2', storeName: 'Mayura', category: 'food', description: '400 g • Soft freshly baked white bread loaf',         deliveryEtaMinutes: 15, inStock: true, imageUrl: '/images/products/milk-bread.jpg',            fallbackImageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=400&fit=crop' },
  { id: 'my04', name: 'Coconut Cookies',         price: 7000,  storeId: 'f2', storeName: 'Mayura', category: 'food', description: '350 g • Classic coconut-flavoured cookies',           deliveryEtaMinutes: 15, inStock: true, imageUrl: '/images/products/coconut-cookies.jpg',       fallbackImageUrl: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=400&h=400&fit=crop' },
  { id: 'my05', name: 'Honey Rusk',              price: 6000,  storeId: 'f2', storeName: 'Mayura', category: 'food', description: '350 g • Sweet honey-glazed toast fingers',            deliveryEtaMinutes: 15, inStock: true, imageUrl: '/images/products/rusks.jpg',                 fallbackImageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=400&fit=crop' },
  { id: 'my06', name: 'Cream Buns',              price: 2500,  storeId: 'f2', storeName: 'Mayura', category: 'food', description: '2 Pieces • Fluffy buns filled with sweet cream',      deliveryEtaMinutes: 15, inStock: true, imageUrl: '/images/products/cream-buns.jpg',            fallbackImageUrl: 'https://images.unsplash.com/photo-1550617931-e17a7b70dce2?w=400&h=400&fit=crop' },
  { id: 'my07', name: 'Pineapple Cake',          price: 38000, storeId: 'f2', storeName: 'Mayura', category: 'food', description: '500 g • Light sponge with pineapple filling',          deliveryEtaMinutes: 25, inStock: true, imageUrl: '/images/products/pineapple-pastry.jpg',      fallbackImageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=400&h=400&fit=crop' },
  { id: 'my08', name: 'Veg Patties',             price: 2000,  storeId: 'f2', storeName: 'Mayura', category: 'food', description: '1 Piece • Flaky pastry with spiced veggie filling',   deliveryEtaMinutes: 15, inStock: true, imageUrl: '/images/products/veg-puff.jpg',              fallbackImageUrl: 'https://images.unsplash.com/photo-1587318712395-6d04fc4db04f?w=400&h=400&fit=crop' },
  { id: 'my09', name: 'Birthday Candles Set',    price: 5000,  storeId: 'f2', storeName: 'Mayura', category: 'food', description: '10 Candles + 1 Star • Celebration set',               deliveryEtaMinutes: 15, inStock: true, imageUrl: '/images/products/birthday-candles.jpg',      fallbackImageUrl: 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=400&h=400&fit=crop' },
  { id: 'my10', name: 'Bread Rolls',             price: 2000,  storeId: 'f2', storeName: 'Mayura', category: 'food', description: '6 Pieces • Soft dinner rolls',                        deliveryEtaMinutes: 15, inStock: true, imageUrl: '/images/products/milk-bread.jpg',            fallbackImageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=400&fit=crop' },
];

// AMBUR BIRIYANI KGF (Restaurant)
const amburProducts: Product[] = [
  { id: 'ab01', name: 'Chicken Dum Biryani',       price: 18000, storeId: 'f3', storeName: 'Ambur Biriyani KGF', category: 'food', description: '750 ml box • Authentic Ambur-style seeraga samba', deliveryEtaMinutes: 35, inStock: true, imageUrl: '/images/products/chicken-biryani.jpg',      fallbackImageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&h=400&fit=crop' },
  { id: 'ab02', name: 'Kushka (Plain Biryani)',     price: 12000, storeId: 'f3', storeName: 'Ambur Biriyani KGF', category: 'food', description: '500 ml box • Biryani rice cooked in meat stock',     deliveryEtaMinutes: 30, inStock: true, imageUrl: '/images/products/kushka.jpg',               fallbackImageUrl: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=400&h=400&fit=crop' },
  { id: 'ab03', name: 'Mutton Biryani',            price: 27000, storeId: 'f3', storeName: 'Ambur Biriyani KGF', category: 'food', description: '750 ml box • Slow-cooked mutton biryani',             deliveryEtaMinutes: 40, inStock: true, imageUrl: '/images/products/mutton-biryani.jpg',       fallbackImageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&h=400&fit=crop' },
  { id: 'ab04', name: 'Chicken 65',               price: 16000, storeId: 'f3', storeName: 'Ambur Biriyani KGF', category: 'food', description: '½ Plate • Deep-fried crispy chicken starter',        deliveryEtaMinutes: 30, inStock: true, imageUrl: '/images/products/chicken-65.jpg',           fallbackImageUrl: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=400&h=400&fit=crop' },
  { id: 'ab05', name: 'Mutton Kheema',            price: 22000, storeId: 'f3', storeName: 'Ambur Biriyani KGF', category: 'food', description: 'Full • Spiced minced mutton curry',                   deliveryEtaMinutes: 35, inStock: true, imageUrl: '/images/products/mutton-kheema.jpg',        fallbackImageUrl: 'https://images.unsplash.com/photo-1545247181-516773cae754?w=400&h=400&fit=crop' },
  { id: 'ab06', name: 'Chicken Curry',            price: 18000, storeId: 'f3', storeName: 'Ambur Biriyani KGF', category: 'food', description: 'Full • Rich Ambur-style chicken curry',               deliveryEtaMinutes: 30, inStock: true, imageUrl: '/images/products/chicken-curry.jpg',        fallbackImageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&h=400&fit=crop' },
  { id: 'ab07', name: 'Raita',                    price: 4000,  storeId: 'f3', storeName: 'Ambur Biriyani KGF', category: 'food', description: '200 ml Cup • Cool onion-tomato raita',               deliveryEtaMinutes: 30, inStock: true, imageUrl: '/images/products/raita.jpg',                fallbackImageUrl: 'https://images.unsplash.com/photo-1558231206-8d6263595166?w=400&h=400&fit=crop' },
  { id: 'ab08', name: 'Salna (Gravy)',             price: 5000,  storeId: 'f3', storeName: 'Ambur Biriyani KGF', category: 'food', description: '200 ml Cup • Spicy kurma-style gravy',               deliveryEtaMinutes: 30, inStock: true, imageUrl: '/images/products/salna.jpg',                fallbackImageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&h=400&fit=crop' },
  { id: 'ab09', name: 'Boiled Egg',               price: 1500,  storeId: 'f3', storeName: 'Ambur Biriyani KGF', category: 'food', description: '2 Pieces • Half-boiled eggs with masala',            deliveryEtaMinutes: 30, inStock: true, imageUrl: '/images/products/boiled-egg.jpg',           fallbackImageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=400&h=400&fit=crop' },
  { id: 'ab10', name: 'Coke 750ml',               price: 4500,  storeId: 'f3', storeName: 'Ambur Biriyani KGF', category: 'food', description: '750 ml Bottle • Chilled Coca-Cola',                  deliveryEtaMinutes: 30, inStock: true, imageUrl: '/images/products/coke.jpg',                 fallbackImageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&h=400&fit=crop' },
];

// AL BAIK (Fried Chicken)
const alBaikProducts: Product[] = [
  { id: 'ak01', name: 'Crispy Fried Chicken (3 Pcs)',    price: 25000, storeId: 'f4', storeName: 'Al Baik', category: 'food', description: '3 Pieces • Signature hot & crispy fried chicken',    deliveryEtaMinutes: 40, inStock: true, imageUrl: '/images/products/fried-chicken.jpg',        fallbackImageUrl: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=400&h=400&fit=crop' },
  { id: 'ak02', name: 'Classic Chicken Zinger Burger',  price: 14000, storeId: 'f4', storeName: 'Al Baik', category: 'food', description: '1 Burger • Crispy chicken fillet with mayo & lettuce', deliveryEtaMinutes: 30, inStock: true, imageUrl: '/images/products/zinger-burger.jpg',        fallbackImageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=400&fit=crop' },
  { id: 'ak03', name: 'Fried Chicken Bucket (8 Pcs)',   price: 59900, storeId: 'f4', storeName: 'Al Baik', category: 'food', description: '8 Pieces • Feast box for the whole family',           deliveryEtaMinutes: 45, inStock: true, imageUrl: '/images/products/chicken-bucket.jpg',       fallbackImageUrl: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=400&h=400&fit=crop' },
  { id: 'ak04', name: 'French Fries',                  price: 7000,  storeId: 'f4', storeName: 'Al Baik', category: 'food', description: 'Large • Crispy golden salted fries',                   deliveryEtaMinutes: 30, inStock: true, imageUrl: '/images/products/french-fries.jpg',         fallbackImageUrl: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&h=400&fit=crop' },
  { id: 'ak05', name: 'Chicken Wings (6 Pcs)',         price: 22000, storeId: 'f4', storeName: 'Al Baik', category: 'food', description: '6 Pieces • Spicy hot buffalo wings',                    deliveryEtaMinutes: 35, inStock: true, imageUrl: '/images/products/chicken-wings.jpg',        fallbackImageUrl: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=400&h=400&fit=crop' },
  { id: 'ak06', name: 'Garlic Dip',                    price: 2000,  storeId: 'f4', storeName: 'Al Baik', category: 'food', description: '50 ml Cup • Creamy roasted garlic dip',               deliveryEtaMinutes: 30, inStock: true, imageUrl: '/images/products/garlic-dip.jpg',           fallbackImageUrl: 'https://images.unsplash.com/photo-1574781664773-3a09ba0a8e6d?w=400&h=400&fit=crop' },
  { id: 'ak07', name: 'Chicken Strips (4 Pcs)',        price: 18000, storeId: 'f4', storeName: 'Al Baik', category: 'food', description: '4 Pieces • Breaded chicken tenders',                   deliveryEtaMinutes: 30, inStock: true, imageUrl: '/images/products/chicken-strips.jpg',       fallbackImageUrl: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=400&h=400&fit=crop' },
  { id: 'ak08', name: 'Coleslaw',                      price: 4500,  storeId: 'f4', storeName: 'Al Baik', category: 'food', description: '150 g Cup • Creamy vegetable coleslaw',               deliveryEtaMinutes: 30, inStock: true, imageUrl: '/images/products/coleslaw.jpg',             fallbackImageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=400&fit=crop' },
  { id: 'ak09', name: 'Chicken Burger Combo',          price: 19000, storeId: 'f4', storeName: 'Al Baik', category: 'food', description: '1 Burger + Fries + Coke combo deal',                  deliveryEtaMinutes: 35, inStock: true, imageUrl: '/images/products/zinger-burger.jpg',        fallbackImageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=400&fit=crop' },
  { id: 'ak10', name: 'Coke 750ml',                   price: 4500,  storeId: 'f4', storeName: 'Al Baik', category: 'food', description: '750 ml Bottle • Chilled Coca-Cola',                   deliveryEtaMinutes: 30, inStock: true, imageUrl: '/images/products/coke.jpg',                 fallbackImageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&h=400&fit=crop' },
];

// AL NAZ (Shawarma & Grills)
const alNazProducts: Product[] = [
  { id: 'an01', name: 'Chicken Shawarma Roll',        price: 9000,  storeId: 'f5', storeName: 'Al Naz', category: 'food', description: '1 Roll • Grilled chicken wrapped with garlic mayo',     deliveryEtaMinutes: 25, inStock: true, imageUrl: '/images/products/shawarma-roll.jpg',        fallbackImageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=400&h=400&fit=crop' },
  { id: 'an02', name: 'Mutton Shawarma Roll',         price: 12000, storeId: 'f5', storeName: 'Al Naz', category: 'food', description: '1 Roll • Grilled mutton strips with tahini sauce',     deliveryEtaMinutes: 25, inStock: true, imageUrl: '/images/products/shawarma-roll.jpg',        fallbackImageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=400&h=400&fit=crop' },
  { id: 'an03', name: 'Paneer Shawarma Roll',         price: 9000,  storeId: 'f5', storeName: 'Al Naz', category: 'food', description: '1 Roll • Grilled paneer with garlic mayo (Veg)',        deliveryEtaMinutes: 25, inStock: true, imageUrl: '/images/products/shawarma-roll.jpg',        fallbackImageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=400&h=400&fit=crop' },
  { id: 'an04', name: 'Chicken Kebab Plate',          price: 22000, storeId: 'f5', storeName: 'Al Naz', category: 'food', description: '3 Skewers • Grilled chicken kebab with salad & bread',  deliveryEtaMinutes: 35, inStock: true, imageUrl: '/images/products/chicken-kebab.jpg',        fallbackImageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400&h=400&fit=crop' },
  { id: 'an05', name: 'Mixed Grill Plate',            price: 34000, storeId: 'f5', storeName: 'Al Naz', category: 'food', description: 'Platter • Chicken + Mutton + Seekh kebab combo',        deliveryEtaMinutes: 40, inStock: true, imageUrl: '/images/products/mixed-grill.jpg',          fallbackImageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400&h=400&fit=crop' },
  { id: 'an06', name: 'Garlic Bread',                price: 5000,  storeId: 'f5', storeName: 'Al Naz', category: 'food', description: '4 Slices • Toasted garlic butter bread',               deliveryEtaMinutes: 20, inStock: true, imageUrl: '/images/products/garlic-bread.jpg',         fallbackImageUrl: 'https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?w=400&h=400&fit=crop' },
  { id: 'an07', name: 'Hummus with Pita',            price: 8000,  storeId: 'f5', storeName: 'Al Naz', category: 'food', description: '200 g • Creamy hummus with warm pita bread',            deliveryEtaMinutes: 20, inStock: true, imageUrl: '/images/products/hummus.jpg',               fallbackImageUrl: 'https://images.unsplash.com/photo-1542444459-94a8e36fbf8e?w=400&h=400&fit=crop' },
  { id: 'an08', name: 'French Fries',               price: 7000,  storeId: 'f5', storeName: 'Al Naz', category: 'food', description: 'Large • Crispy golden salted fries',                    deliveryEtaMinutes: 20, inStock: true, imageUrl: '/images/products/french-fries.jpg',         fallbackImageUrl: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&h=400&fit=crop' },
  { id: 'an09', name: 'Garlic Dip',                 price: 2000,  storeId: 'f5', storeName: 'Al Naz', category: 'food', description: '50 ml Cup • Creamy garlic toum dip',                    deliveryEtaMinutes: 20, inStock: true, imageUrl: '/images/products/garlic-dip.jpg',           fallbackImageUrl: 'https://images.unsplash.com/photo-1574781664773-3a09ba0a8e6d?w=400&h=400&fit=crop' },
  { id: 'an10', name: 'Coke 750ml',                 price: 4500,  storeId: 'f5', storeName: 'Al Naz', category: 'food', description: '750 ml Bottle • Chilled Coca-Cola',                     deliveryEtaMinutes: 20, inStock: true, imageUrl: '/images/products/coke.jpg',                 fallbackImageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&h=400&fit=crop' },
];

export const mockFoodProducts: Product[] = [
  ...bakioProducts,
  ...mayuraProducts,
  ...amburProducts,
  ...alBaikProducts,
  ...alNazProducts,
];
