import type { Store, Product, Order, Merchant } from '../types/snapit-types';

export interface ProductInventoryItem extends Product {
  stockCount: number;
  availability: 'AVAILABLE' | 'OUT OF STOCK' | 'UNLISTED';
  description?: string;
}

export interface HistoricalDateGroup {
  dateKey: string; // e.g. "30-Jul-2026 Thursday"
  orderCount: number;
  collectedPaise: number;
  rejectedCount: number;
  lostPaise: number;
  orders: Order[];
}

export const mockMerchants: Merchant[] = [
  {
    uid: 'm_kitchen',
    name: 'Mr & Mrs Kitchen Partner',
    phone: '+91 98450 22334',
    role: 'merchant',
    storeId: 'f2',
    storeName: 'MR & MRS KITCHEN',
  },
  {
    uid: 'm_babujuice',
    name: 'Babu (Juice Center)',
    phone: '+91 98450 33445',
    role: 'merchant',
    storeId: 'f3',
    storeName: 'Babu Juice Shop',
  },
  {
    uid: 'm_coolshop',
    name: 'Cool Shop Admin',
    phone: '+91 98450 44556',
    role: 'merchant',
    storeId: 'f4',
    storeName: 'Cool Shop',
  },
  {
    uid: 'm_mhetha',
    name: 'Ramesh Mhetha',
    phone: '+91 99001 23456',
    role: 'merchant',
    storeId: 'g1',
    storeName: 'Mhetha Stores',
  },
  {
    uid: 'm_amburx',
    name: 'Kareem Pasha',
    phone: '+91 97412 34567',
    role: 'merchant',
    storeId: 'f1',
    storeName: 'Ambur Biriyani KGF',
  },
  {
    uid: 'm_nandhini',
    name: 'Suresh Kumar',
    phone: '+91 94480 33445',
    role: 'merchant',
    storeId: 'd1',
    storeName: 'Nandhini KGF',
  },
];

export const mockStores: Store[] = [
  {
    id: 'f2',
    name: 'MR & MRS KITCHEN',
    logoUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400&auto=format&fit=crop&q=80',
    rating: 4.8,
    category: 'food',
    isOpen: false,
    address: 'Robertsonpet, KGF',
  },
  {
    id: 'f3',
    name: 'Babu Juice Shop',
    logoUrl: 'https://images.unsplash.com/photo-1622597467836-f3285f2131b7?w=400&auto=format&fit=crop&q=80',
    rating: 4.7,
    category: 'food',
    isOpen: false,
    address: 'Andersonpet Main Road, KGF',
  },
  {
    id: 'f4',
    name: 'Cool Shop',
    logoUrl: 'https://raw.githubusercontent.com/DhaKavdesigners/snapit-pwa/main/snapit-pwa/Images/stores/cool-shop/special_kool.jpg',
    rating: 4.8,
    category: 'food',
    isOpen: false,
    address: 'Geetha Road, Robertsonpet, KGF',
  },
  {
    id: 'f1',
    name: 'Ambur Biriyani KGF',
    logoUrl: 'https://raw.githubusercontent.com/DhaKavdesigners/snapit-pwa/main/snapit-pwa/Images/stores/ambur-biriyani-kgf/venus%20ambur%20biriyani.jpg',
    rating: 4.8,
    category: 'food',
    isOpen: false,
    address: 'Andersonpet Main Road, KGF',
  },
  {
    id: 'g1',
    name: 'Mhetha Stores',
    logoUrl: '/images/stores/metha-stores.avif',
    rating: 4.8,
    category: 'grocery',
    isOpen: false,
    address: 'Main Road, Andersonpet, KGF',
  },
  {
    id: 'd1',
    name: 'Nandhini KGF',
    logoUrl: '/images/stores/nandhini-kgf/logo.jpg',
    rating: 4.8,
    category: 'grocery',
    isOpen: false,
    address: 'South Gilberts Road, Andersonpet, KGF',
  },
];

export const mockProductsByStore: Record<string, ProductInventoryItem[]> = {
  // MR & MRS KITCHEN (f2)
  f2: [
    // 1. Starters
    {
      id: 'mmk_st_01',
      storeId: 'f2',
      name: 'French Fries',
      price: 5900,
      category: 'Starters',
      imageUrl: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?w=400&auto=format&fit=crop&q=80',
      deliveryEtaMinutes: 10,
      inStock: true,
      stockCount: 50,
      availability: 'AVAILABLE',
      description: 'Crispy golden salted french fries served with ketchup',
    },
    {
      id: 'mmk_st_02',
      storeId: 'f2',
      name: 'Peri Peri French Fries',
      price: 6900,
      category: 'Starters',
      imageUrl: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&auto=format&fit=crop&q=80',
      deliveryEtaMinutes: 10,
      inStock: true,
      stockCount: 50,
      availability: 'AVAILABLE',
      description: 'Crisp french fries tossed in spicy peri peri seasoning',
    },
    {
      id: 'mmk_st_03',
      storeId: 'f2',
      name: 'Chicken Cheese Balls (3 pcs)',
      price: 5900,
      category: 'Starters',
      imageUrl: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=400&auto=format&fit=crop&q=80',
      deliveryEtaMinutes: 12,
      inStock: true,
      stockCount: 50,
      availability: 'AVAILABLE',
      description: 'Crispy golden fried balls with molten cheese & seasoned minced chicken',
    },
    {
      id: 'mmk_st_04',
      storeId: 'f2',
      name: 'Smiley (4 pcs)',
      price: 4900,
      category: 'Starters',
      imageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=400&auto=format&fit=crop&q=80',
      deliveryEtaMinutes: 10,
      inStock: true,
      stockCount: 50,
      availability: 'AVAILABLE',
      description: 'Crispy fried potato smileys with delicious light seasoning',
    },
    {
      id: 'mmk_st_05',
      storeId: 'f2',
      name: 'Cheese Corn Nuggets (3 pcs)',
      price: 4900,
      category: 'Starters',
      imageUrl: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=400&auto=format&fit=crop&q=80',
      deliveryEtaMinutes: 10,
      inStock: true,
      stockCount: 50,
      availability: 'AVAILABLE',
      description: 'Golden crunchy nuggets loaded with melted cheese & juicy sweet corn',
    },

    // 2. Rolls
    {
      id: 'mmk_rl_01',
      storeId: 'f2',
      name: 'Chicken Keema Roll',
      price: 7900,
      category: 'Rolls',
      imageUrl: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=400&auto=format&fit=crop&q=80',
      deliveryEtaMinutes: 12,
      inStock: true,
      stockCount: 50,
      availability: 'AVAILABLE',
      description: 'Spiced minced chicken keema with onions & sauces in a flaky paratha roll',
    },
    {
      id: 'mmk_rl_02',
      storeId: 'f2',
      name: 'Chicken Crunchy Roll',
      price: 7900,
      category: 'Rolls',
      imageUrl: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=400&auto=format&fit=crop&q=80',
      deliveryEtaMinutes: 12,
      inStock: true,
      stockCount: 50,
      availability: 'AVAILABLE',
      description: 'Crunchy chicken strips rolled with spicy mayo and crisp onions',
    },
    {
      id: 'mmk_rl_03',
      storeId: 'f2',
      name: 'Paneer Roll',
      price: 5900,
      category: 'Rolls',
      imageUrl: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=400&auto=format&fit=crop&q=80',
      deliveryEtaMinutes: 12,
      inStock: true,
      stockCount: 50,
      availability: 'AVAILABLE',
      description: 'Soft spiced paneer cubes wrapped with fresh sliced onions & mint sauce',
    },
    {
      id: 'mmk_rl_04',
      storeId: 'f2',
      name: 'Veg. Roll',
      price: 6900,
      category: 'Rolls',
      imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&auto=format&fit=crop&q=80',
      deliveryEtaMinutes: 10,
      inStock: true,
      stockCount: 50,
      availability: 'AVAILABLE',
      description: 'Crisp vegetable filling rolled with herbs and tangy chutney',
    },
    {
      id: 'mmk_rl_05',
      storeId: 'f2',
      name: 'Egg Roll',
      price: 6900,
      category: 'Rolls',
      imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&auto=format&fit=crop&q=80',
      deliveryEtaMinutes: 10,
      inStock: true,
      stockCount: 50,
      availability: 'AVAILABLE',
      description: 'Double egg omelette layered paratha roll with crunchy onions & green chilies',
    },

    // 3. Sandwich
    {
      id: 'mmk_sw_01',
      storeId: 'f2',
      name: 'Chicken Sandwich',
      price: 5900,
      category: 'Sandwich',
      imageUrl: 'https://images.unsplash.com/photo-1521390188846-e2a39b7ef4a8?w=400&auto=format&fit=crop&q=80',
      deliveryEtaMinutes: 10,
      inStock: true,
      stockCount: 50,
      availability: 'AVAILABLE',
      description: 'Shredded seasoned chicken mixed with creamy mayo between toasted bread',
    },
    {
      id: 'mmk_sw_02',
      storeId: 'f2',
      name: 'Paneer Sandwich',
      price: 5900,
      category: 'Sandwich',
      imageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=400&auto=format&fit=crop&q=80',
      deliveryEtaMinutes: 10,
      inStock: true,
      stockCount: 50,
      availability: 'AVAILABLE',
      description: 'Fresh spiced cottage cheese slices grilled between crisp golden bread',
    },
    {
      id: 'mmk_sw_03',
      storeId: 'f2',
      name: 'Egg Sandwich',
      price: 3900,
      category: 'Sandwich',
      imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=400&auto=format&fit=crop&q=80',
      deliveryEtaMinutes: 8,
      inStock: true,
      stockCount: 50,
      availability: 'AVAILABLE',
      description: 'Fluffy seasoned egg omelette placed inside toasted buttered bread',
    },

    // 4. Burgers
    {
      id: 'mmk_bg_01',
      storeId: 'f2',
      name: 'Chicken Burger',
      price: 6900,
      category: 'Burgers',
      imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&auto=format&fit=crop&q=80',
      deliveryEtaMinutes: 12,
      inStock: true,
      stockCount: 50,
      availability: 'AVAILABLE',
      description: 'Juicy chicken patty with crisp lettuce, onion slices & classic burger mayo',
    },
    {
      id: 'mmk_bg_02',
      storeId: 'f2',
      name: 'Double Chicken Burger',
      price: 7900,
      category: 'Burgers',
      imageUrl: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=400&auto=format&fit=crop&q=80',
      deliveryEtaMinutes: 15,
      inStock: true,
      stockCount: 50,
      availability: 'AVAILABLE',
      description: 'Double stacked chicken patties with cheese slice and creamy pepper mayo',
    },
    {
      id: 'mmk_bg_03',
      storeId: 'f2',
      name: 'Paneer Burger',
      price: 6900,
      category: 'Burgers',
      imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=400&auto=format&fit=crop&q=80',
      deliveryEtaMinutes: 12,
      inStock: true,
      stockCount: 50,
      availability: 'AVAILABLE',
      description: 'Crispy breaded paneer patty topped with fresh veggies and spicy dressing',
    },
    {
      id: 'mmk_bg_04',
      storeId: 'f2',
      name: 'Veg. Burger',
      price: 5900,
      category: 'Burgers',
      imageUrl: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=400&auto=format&fit=crop&q=80',
      deliveryEtaMinutes: 10,
      inStock: true,
      stockCount: 50,
      availability: 'AVAILABLE',
      description: 'Crunchy mixed veg patty with fresh lettuce, tomato & creamy spread',
    },
    {
      id: 'mmk_bg_05',
      storeId: 'f2',
      name: 'Crunchy Burger',
      price: 6900,
      category: 'Burgers',
      imageUrl: 'https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?w=400&auto=format&fit=crop&q=80',
      deliveryEtaMinutes: 12,
      inStock: true,
      stockCount: 50,
      availability: 'AVAILABLE',
      description: 'Extra crispy golden fried chicken fillet with spicy chipotle mayo',
    },

    // 5. Fried Chicken
    {
      id: 'mmk_fc_01',
      storeId: 'f2',
      name: 'Chicken Lollipop (3 pcs)',
      price: 8900,
      category: 'Fried Chicken',
      imageUrl: 'https://images.unsplash.com/photo-1527477378377-f509e51c6b3e?w=400&auto=format&fit=crop&q=80',
      deliveryEtaMinutes: 15,
      inStock: true,
      stockCount: 50,
      availability: 'AVAILABLE',
      description: 'Crispy fried chicken winglets served with spicy Schezwan dip',
    },
    {
      id: 'mmk_fc_02',
      storeId: 'f2',
      name: 'Spicy Wings (4 pcs)',
      price: 8900,
      category: 'Fried Chicken',
      imageUrl: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=400&auto=format&fit=crop&q=80',
      deliveryEtaMinutes: 15,
      inStock: true,
      stockCount: 50,
      availability: 'AVAILABLE',
      description: 'Juicy chicken wings coated in fiery hot spices and fried to a crunch',
    },
    {
      id: 'mmk_fc_03',
      storeId: 'f2',
      name: 'Hot Wings (3 pcs)',
      price: 6900,
      category: 'Fried Chicken',
      imageUrl: 'https://images.unsplash.com/photo-1524182576066-1be9613774db?w=400&auto=format&fit=crop&q=80',
      deliveryEtaMinutes: 12,
      inStock: true,
      stockCount: 50,
      availability: 'AVAILABLE',
      description: 'Crispy golden fried chicken wings with mild hot seasoning',
    },
    {
      id: 'mmk_fc_04',
      storeId: 'f2',
      name: 'Chicken Popcorn (10 pcs)',
      price: 7900,
      category: 'Fried Chicken',
      imageUrl: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=400&auto=format&fit=crop&q=80',
      deliveryEtaMinutes: 12,
      inStock: true,
      stockCount: 50,
      availability: 'AVAILABLE',
      description: 'Bite-sized crunchy boneless chicken pops dusted with herbs',
    },
    {
      id: 'mmk_fc_05',
      storeId: 'f2',
      name: 'Chicken Leg (1 pc)',
      price: 6900,
      category: 'Fried Chicken',
      imageUrl: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400&auto=format&fit=crop&q=80',
      deliveryEtaMinutes: 12,
      inStock: true,
      stockCount: 50,
      availability: 'AVAILABLE',
      description: 'Crispy fried marinated chicken drumstick bursting with flavor',
    },

    // 6. Mojitos
    {
      id: 'mmk_mj_01',
      storeId: 'f2',
      name: 'Blue Mojito',
      price: 6900,
      category: 'Mojitos',
      imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=400&auto=format&fit=crop&q=80',
      deliveryEtaMinutes: 8,
      inStock: true,
      stockCount: 50,
      availability: 'AVAILABLE',
      description: 'Chilled blue curacao cooler with crushed fresh mint, lime and sparkling fizz',
    },
    {
      id: 'mmk_mj_02',
      storeId: 'f2',
      name: 'Mint Mojito',
      price: 6900,
      category: 'Mojitos',
      imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=400&auto=format&fit=crop&q=80',
      deliveryEtaMinutes: 8,
      inStock: true,
      stockCount: 50,
      availability: 'AVAILABLE',
      description: 'Classic refreshing virgin mojito with mint sprigs, lime wedge and sparkling soda',
    },
    {
      id: 'mmk_mj_03',
      storeId: 'f2',
      name: 'Litchi Mojito',
      price: 5900,
      category: 'Mojitos',
      imageUrl: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=400&auto=format&fit=crop&q=80',
      deliveryEtaMinutes: 8,
      inStock: true,
      stockCount: 50,
      availability: 'AVAILABLE',
      description: 'Sweet and fragrant litchi mocktail with muddled mint leaves and lime',
    },
  ],

  // Cool Shop (f4) - Special Kool & Special Moore
  f4: [
    {
      id: 'cs_01',
      storeId: 'f4',
      name: 'Special Kool',
      price: 4000,
      category: 'Traditional Coolers',
      imageUrl: 'https://raw.githubusercontent.com/DhaKavdesigners/snapit-pwa/main/snapit-pwa/Images/stores/cool-shop/special_kool.jpg',
      deliveryEtaMinutes: 10,
      inStock: true,
      stockCount: 50,
      availability: 'AVAILABLE',
      description: 'Authentic Keppai / Ragi Kool garnished with finely chopped shallots, served with spicy mor milagai (sun-dried curd chillies) & pickles',
    },
    {
      id: 'cs_02',
      storeId: 'f4',
      name: 'Special Moore',
      price: 3000,
      category: 'Traditional Coolers',
      imageUrl: 'https://raw.githubusercontent.com/DhaKavdesigners/snapit-pwa/main/snapit-pwa/Images/stores/cool-shop/special_moore.jpg',
      deliveryEtaMinutes: 8,
      inStock: true,
      stockCount: 50,
      availability: 'AVAILABLE',
      description: 'Refreshing traditional spiced buttermilk infused with mustard tempering, cumin, ginger, curry leaves & coriander, accompanied by mor milagai',
    },
  ],

  // MHETHA STORES (Grocery Store with detailed categories)
  g1: [
    {
      id: 'ms01',
      name: 'Maggi 2-Minute Noodles (Pack of 2)',
      price: 2800, // ₹28
      imageUrl: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?w=400&auto=format&fit=crop&q=80',
      storeId: 'g1',
      category: 'Noodles & Snacks',
      deliveryEtaMinutes: 10,
      inStock: true,
      stockCount: 120,
      availability: 'AVAILABLE',
      description: '140 g Pack of 2 instant masala noodles',
    },
    {
      id: 'ms02',
      name: 'Fortune Sunflower Oil (1L Pouch)',
      price: 13500, // ₹135
      imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&auto=format&fit=crop&q=80',
      storeId: 'g1',
      category: 'Edible Oils',
      deliveryEtaMinutes: 10,
      inStock: true,
      stockCount: 40,
      availability: 'AVAILABLE',
      description: '1 Litre refined sunflower pouch',
    },
    {
      id: 'ms03',
      name: 'Tata Tea Gold (250g)',
      price: 4500, // ₹45
      imageUrl: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&auto=format&fit=crop&q=80',
      storeId: 'g1',
      category: 'Tea & Coffee',
      deliveryEtaMinutes: 10,
      inStock: true,
      stockCount: 65,
      availability: 'AVAILABLE',
      description: '250 g rich & aromatic tea blend',
    },
    {
      id: 'ms04',
      name: 'Aashirvaad Shudh Chakki Atta (5kg)',
      price: 24500, // ₹245
      imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&auto=format&fit=crop&q=80',
      storeId: 'g1',
      category: 'Atta & Flours',
      deliveryEtaMinutes: 10,
      inStock: true,
      stockCount: 30,
      availability: 'AVAILABLE',
      description: '100% whole wheat grain flour with natural dietary fiber',
    },
    {
      id: 'ms05',
      name: 'Surf Excel Easy Wash (1kg)',
      price: 13000, // ₹130
      imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=400&auto=format&fit=crop&q=80',
      storeId: 'g1',
      category: 'Soaps & Detergents',
      deliveryEtaMinutes: 10,
      inStock: true,
      stockCount: 50,
      availability: 'AVAILABLE',
      description: 'Advanced stain removal washing powder',
    },
  ],

  // NANDHINI KGF (Daily Essentials & Dairy)
  d1: [
    {
      id: 'nd01',
      name: 'Nandini Pasteurised Toned Milk (500ml)',
      price: 2400, // ₹24
      imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&auto=format&fit=crop&q=80',
      storeId: 'd1',
      category: 'Milk & Curd',
      deliveryEtaMinutes: 8,
      inStock: true,
      stockCount: 80,
      availability: 'AVAILABLE',
      description: 'Fresh pasteurised toned milk with 3.0% fat',
    },
    {
      id: 'nd02',
      name: 'Nandini Special Curd (500g)',
      price: 2600, // ₹26
      imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&auto=format&fit=crop&q=80',
      storeId: 'd1',
      category: 'Milk & Curd',
      deliveryEtaMinutes: 8,
      inStock: true,
      stockCount: 44,
      availability: 'AVAILABLE',
      description: 'Thick & delicious pure pasteurised curd pouch',
    },
    {
      id: 'nd03',
      name: 'Nandini Pure Cow Ghee (500ml Pouch)',
      price: 32000, // ₹320
      imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=400&auto=format&fit=crop&q=80',
      storeId: 'd1',
      category: 'Butter & Ghee',
      deliveryEtaMinutes: 8,
      inStock: false,
      stockCount: 0,
      availability: 'OUT OF STOCK',
      description: 'Traditional aroma pure cow milk ghee',
    },
    {
      id: 'nd04',
      name: 'Nandini Fresh Paneer (200g)',
      price: 9500, // ₹95
      imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400&auto=format&fit=crop&q=80',
      storeId: 'd1',
      category: 'Paneer & Cheese',
      deliveryEtaMinutes: 8,
      inStock: true,
      stockCount: 35,
      availability: 'AVAILABLE',
      description: 'Soft and creamy malai paneer block for cooking',
    },
    {
      id: 'nd05',
      name: 'Nandini Pasteurized Table Butter (100g)',
      price: 5600, // ₹56
      imageUrl: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=400&auto=format&fit=crop&q=80',
      storeId: 'd1',
      category: 'Butter & Ghee',
      deliveryEtaMinutes: 8,
      inStock: true,
      stockCount: 40,
      availability: 'AVAILABLE',
      description: 'Delicious salted table butter block',
    },
  ],

  // AMBUR BIRIYANI KGF (Restaurant Food)
  f3: [
    {
      id: 'ab01',
      name: 'Special Chicken Dum Biryani',
      price: 18000, // ₹180
      imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&auto=format&fit=crop&q=80',
      storeId: 'f3',
      category: 'Biryani Specials',
      deliveryEtaMinutes: 25,
      inStock: true,
      stockCount: 50,
      availability: 'AVAILABLE',
      description: 'Authentic seeraga samba rice cooked with tender spiced chicken & eggs',
    },
    {
      id: 'ab02',
      name: 'Chicken 65 (Boneless Starter)',
      price: 15000, // ₹150
      imageUrl: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=400&auto=format&fit=crop&q=80',
      storeId: 'f3',
      category: 'Starters & Grills',
      deliveryEtaMinutes: 20,
      inStock: true,
      stockCount: 40,
      availability: 'AVAILABLE',
      description: 'Crispy deep fried chicken tossed with curry leaves & green chilies',
    },
    {
      id: 'ab03',
      name: 'Paneer Butter Masala (Gravy)',
      price: 16000, // ₹160
      imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400&auto=format&fit=crop&q=80',
      storeId: 'f3',
      category: 'Veg Gravies',
      deliveryEtaMinutes: 20,
      inStock: true,
      stockCount: 30,
      availability: 'AVAILABLE',
      description: 'Rich tomato cashew gravy with soft paneer cubes',
    },
  ],
};

export const initialHistoricalGroups: HistoricalDateGroup[] = [
  {
    dateKey: 'Today (Live Activity)',
    orderCount: 0,
    collectedPaise: 0,
    rejectedCount: 0,
    lostPaise: 0,
    orders: [],
  },
];
